Q.1 Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [33]:
!pip install numpy
!pip install pandas


   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.5 MB 5.0 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/11.5 MB 5.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.7/11.5 MB 4.2 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.5 MB 4.6 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.5 MB 4.9 MB/s eta 0:00:02
   --------------------------- ------------ 7.9/11.5 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 5.2 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 5.2 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 4.9 MB/s eta 0:00:01
   -------

In [4]:
import numpy as np
arr = np.arange(6)
print("Array:", arr)


Array: [0 1 2 3 4 5]


Q.2 Given a NumPy array 'arr', check if its data type is float64.
 arr = np.array([1.5, 2.6, 3.7])

In [5]:
import numpy as np
arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64
print(is_float64)

True


Q.3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [6]:
import numpy as np
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


Q.4 Convert an existing NumPy array 'arr' of integers to float32 data type.

In [7]:
import numpy as np
integer_array = np.array(["1.1", "2.2", "3.3", "4.4"])
float_array = np.array(integer_array, dtype=float)
print("Original Array (Integer):", integer_array)
print("Converted Array (Float):", float_array)


Original Array (Integer): ['1.1' '2.2' '3.3' '4.4']
Converted Array (Float): [1.1 2.2 3.3 4.4]


Q.5 Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [8]:
 import numpy as np
# Assuming 'arr' is your numpy array with float64 data type
arr = np.array([1.0, 2.0, 3.0], dtype=np.float64)
# Convert the array to float32
arr_float32 = arr.astype(np.float32)
print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3.]
float32


Q.6 Write a function array attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [9]:
import numpy as np
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
attributes = array_attributes(arr)
print(attributes) 


((2, 3), 6, dtype('float64'))


Q.7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [10]:
import numpy as np
def array_dimension(arr):
    return arr.ndim
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)
print(dimension) 


2


Q.8 Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [11]:
import numpy as np
def item_size_info(array):
    item_size = array.itemsize
    total_size = array.nbytes
    return item_size, total_size
    
arr = np.array([1, 2, 3, 4, 5])
item_size, total_size = item_size_info(arr)
print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")


Item size: 8 bytes
Total size: 40 bytes


Q.9 Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [12]:
import numpy as np
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))  


(24, 8)


Q.10 Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [13]:
import numpy as np
def shape_stride_relationship(array):
    shape = array.shape
    strides = array.strides
    return shape, strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (24, 8)


Q.11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [14]:
 import numpy as np
def create_zeros_array(n):
    return np.zeros(n)
    
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0.]


Q.12 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [15]:
import numpy as np
def create_ones_matrix(rows, cols):
    """
    Create a 2D NumPy array filled with ones.
    Parameters:
    rows (int): Number of rows in the matrix.
    cols (int): Number of columns in the matrix.
    Returns:
    np.ndarray: A 2D array of shape (rows, cols) filled with ones.
    """
    return np.ones((rows, cols))
    
matrix = create_ones_matrix(3, 4)
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q.13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [16]:
 import numpy as np
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

array = generate_range_array(0, 10, 2)
print(array)


[0 2 4 6 8]


Q.14 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [17]:
 import numpy as np
def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q.15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [18]:
import numpy as np
def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q.16 Write a function that takes a Python list and converts it into a NumPy array.

In [19]:
import numpy as np
def list_to_numpy_array(lst):
    return np.array(lst)

my_list = [1, 2, 3, 4, 5]
my_array = list_to_numpy_array(my_list)
print(my_array)


[1 2 3 4 5]


Q.17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [20]:
import numpy as np
# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])
# Create a view of the original array
view_array = original_array.view()
# Modify the original array
original_array[0] = 42
# Print both arrays to see the effect
print("Original array:", original_array)
print("View array:", view_array)


Original array: [42  2  3  4  5]
View array: [42  2  3  4  5]


Q.18 Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [21]:
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
    """
    Concatenates two NumPy arrays along the specified axis.
    Args:
        arr1 (np.ndarray): First array.
        arr2 (np.ndarray): Second array.
        axis (int, optional): Axis along which to concatenate. Default is 0 (vertical concatenation).
    Returns:
        np.ndarray: Concatenated array.
    """
    return np.concatenate((arr1, arr2), axis=axis)
# Example usage:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
result = concatenate_arrays(a, b, axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


Q.19 Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. Concatenate’.

In [22]:
import numpy as np
# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])
# Concatenate the arrays horizontally
result = np.concatenate((array1, array2), axis=1)
print(result)


[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Q.20 Write a function that vertically stacks multiple NumPy arrays given as a list.

In [25]:
import numpy as np
def vertical_stack(arrays):
    """
    Vertically stack multiple NumPy arrays given as a list.
    Parameters:
    arrays (list of np.ndarray): List of NumPy arrays to be stacked.
    Returns:
    np.ndarray: Vertically stacked array."""
    return np.vstack(arrays)
# Example usage:
array1 = np


Q.21 Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [26]:
import numpy as np
def create_integer_array(start, stop, step):
    """
    Create an array of integers within a specified range with a given step size.
    Parameters:
    start (int): The starting value of the range.
    stop (int): The end value of the range (inclusive).
    step (int): The step size between each value in the range.
    Returns:
    numpy.ndarray: An array of integers within the specified range.
    """
    return np.arange(start, stop + 1, step)
# Example usage:
array = create_integer_array(1, 10, 2)
print(array)


[1 3 5 7 9]


Q.22 Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [27]:
import numpy as np
def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

values = generate_equally_spaced_values()
print(values)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q.23 Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [28]:
import numpy as np
def create_log_space_array():
    
    log_space_array = np.logspace(0, 3, num=5)
    return log_space_array

array = create_log_space_array()
print(array)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


Q.24 Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [35]:
import numpy as np
import pandas as pd

array = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(array, columns=['Column1', 'Column2', 'Column3'])

print(df)



   Column1  Column2  Column3
0       24       83       41
1        5       47        4
2       23       74       78
3       45       92       88
4        6       92       36


Q.25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [34]:
import pandas as pd
import numpy as np
def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


data = {'A': [1, -2, 3, -4, 5], 'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
df = replace_negatives_with_zeros(df, 'A')
print("\nDataFrame after replacing negatives in column 'A' with zeros:")
print(df)


Original DataFrame:
   A  B
0  1  5
1 -2 -6
2  3  7
3 -4 -8
4  5  9

DataFrame after replacing negatives in column 'A' with zeros:
   A  B
0  1  5
1  0 -6
2  3  7
3  0 -8
4  5  9


Q.26 Access the 3rd element from the given NumPy array. 

In [37]:

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)


30


Q.27 Retrieve the element at index (1, 2) from the 2D NumPy array. 
arr_2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

In [38]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
print(element)

6


Q.28 Using boolean indexing, extract elements greater than 5 from the given NumPy array. 
arr = np.array([3, 8, 2, 10, 5, 7])

In [39]:
import numpy as np
# Given array
arr = np.array([3, 8, 2, 10, 5, 7])
# Boolean indexing to extract elements greater than 5
result = arr[arr > 5]
print(result)


[ 8 10  7]


Q.29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[2:6]  # Slicing from index 2 to 5 (inclusive)
print(sliced_arr)


[3 4 5 6]


In [ ]:
Q.30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array. 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
import numpy as np
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
# Slicing to get the desired sub-array
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


Q.31 Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [42]:
import numpy as np
def extract_elements(arr, indices):
    """
    Extract elements from a 2D array based on provided indices.
    Parameters:
    arr (numpy.ndarray): The input 2D array.
    indices (numpy.ndarray): The array of indices.
    Returns:
    numpy.ndarray: The extracted elements in the specified order.
    """
    return np.take(arr, indices)
# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([0, 4, 8])
result = extract_elements(arr, indices)
print(result)


[1 5 9]


Q.32  Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing

In [45]:
import numpy as np
def filter_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]
# Example usage:
arr = np.array([1, 2, 3, 4, 5])
threshold = 3
filtered_arr = filter_greater_than_threshold(arr, threshold)
print(filtered_arr)  # Output: [4 5]



[4 5]


Q.33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [46]:
import numpy as np
def extract_elements_3d(array, depth_indices, row_indices, col_indices):
    
    # Ensure the indices arrays are numpy arrays
    depth_indices = np.asarray(depth_indices)
    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)
    # Use advanced indexing to extract the elements
    extracted_elements = array[depth_indices, row_indices, col_indices]
    
    return extracted_elements

array_3d = np.random.randint(0, 100, size=(4, 4, 4))
depth_indices = np.array([0, 1, 2])
row_indices = np.array([1, 2, 3])
col_indices = np.array([2, 3, 1])
extracted_elements = extract_elements_3d(array_3d, depth_indices, row_indices, col_indices)
print("Original 3D array:\n", array_3d)
print("Extracted elements:\n", extracted_elements)


Original 3D array:
 [[[40 40  8 59]
  [69 88 72 71]
  [43 44 31 55]
  [47 29 13 47]]

 [[99  4  6 68]
  [11 97 11 68]
  [44 99 30 96]
  [94 20 75  2]]

 [[15 47 82 53]
  [39 87 42 91]
  [71 17 59 21]
  [98 56 94 27]]

 [[29 84 45 94]
  [ 2 31 83 12]
  [90 66  1 11]
  [56 95  2 48]]]
Extracted elements:
 [72 96 56]


Q.34 Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [47]:
import numpy as np
def filter_array(arr, condition1, condition2):
    
    return arr[condition1 & condition2]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition1 = arr > 3
condition2 = arr < 8
filtered_arr = filter_array(arr, condition1, condition2)
print(filtered_arr)  # Output: [4 5 6 7]


[4 5 6 7]


Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [48]:
import numpy as np
def extract_elements(arr, row_indices, col_indices):
    
    return arr[row_indices, col_indices]

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_elements = extract_elements(arr, row_indices, col_indices)
print(extracted_elements)  # Output: [20 60 70]


[20 60 70]


Q. 36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [49]:
import numpy as np
# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# Add scalar value 5 to each element
result = arr + 5
print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Q.37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [50]:
import numpy as np
# Define the arrays
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])
# Multiply each row of arr2 by the corresponding element in arr1
result = arr2 * arr1.T
print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


Q.38 Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [51]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])  # Shape (4, 3)

arr1_reshaped = arr1.T  
# Add arr1 to each row of arr2
result = arr2 + arr1_reshaped
print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


Q.39 Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting. 

In [52]:
import numpy as np
# Define the arrays
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
# Add the arrays using broadcasting
result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


Q.40 Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility

In [54]:
import numpy as np

# Define the arrays
arr1 = np.random.randint(1, 10, (2, 3))
arr2 = np.random.randint(1, 10, (2, 2))

# Reshape arr2 to make it compatible for broadcasting
arr2_reshaped = arr2[:, :, np.newaxis]

# Perform the multiplication
result = arr1 * arr2_reshaped

# Display the arrays and the result
print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("arr2 reshaped:\n", arr2_reshaped)
print("Result:\n", result)



arr1:
 [[8 3 8]
 [3 9 3]]
arr2:
 [[7 8]
 [6 7]]
arr2 reshaped:
 [[[7]
  [8]]

 [[6]
  [7]]]
Result:
 [[[56 21 56]
  [24 72 24]]

 [[48 18 48]
  [21 63 21]]]


Q.41 Calculate column-wise mean for the given array
arr = np.array([[1, 2, 3], [4, 5, 6]]) 

In [56]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


Q.42 Find maximum value in each row of the given array: 
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [57]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)


[3 6]


Q.43 For the given array, find indices of maximum value in each column. 
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [58]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)
print(column_max_indices)


[1 1 1]


In [ ]:
Q.44 For the given array, apply custom function to calculate moving sum along rows. 
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [60]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Define a custom function to calculate the moving sum along rows
def moving_sum(arr, window_size):
    result = np.zeros_like(arr)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            start = max(0, j - window_size + 1)
            result[i, j] = np.sum(arr[i, start:j+1])
    return result

# Calculate the moving sum with a window size of 2
window_size = 2
moving_sum_result = moving_sum(arr, window_size)

# Display the result
print("Original array:\n", arr)
print("Moving sum along rows with window size {}:\n{}".format(window_size, moving_sum_result))



Original array:
 [[1 2 3]
 [4 5 6]]
Moving sum along rows with window size 2:
[[ 1  3  5]
 [ 4  9 11]]


Q.45 n the given array, check if all elements in each column are even. 
arr = np.array([[2, 4, 6], [3, 5, 7]]).


In [61]:
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns) 


[False False False]


Q.46 Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6]).

In [62]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

def reshape_array(arr, m, n):
    return arr.reshape(m, n)
m, n = 2, 3  
reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


Q.47 Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [63]:
import numpy as np

# Function to flatten a matrix
def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


Q.48 Write a function that concatenates two given arrays along a specified axis. 
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


In [64]:
import numpy as np
# Function to concatenate two arrays along a specified axis
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)  # Concatenate along rows
print(concatenated_array)
concatenated_array = concatenate_arrays(array1, array2, axis=1)  # Concatenate along columns
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Q.49 Create a function that splits an array into multiple sub-arrays along a specified axis. 
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [65]:
import numpy as np
# Function to split an array into multiple sub-arrays along a specified axis
def split_array(array, indices_or_sections, axis=0):
    return np.split(array, indices_or_sections, axis=axis)
# Example usage
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Split the array into 3 sub-arrays along axis 0 (rows)
split_arrays = split_array(original_array, 3, axis=0)
for sub_array in split_arrays:
    print(sub_array)
# Split the array into 3 sub-arrays along axis 1 (columns)
split_arrays = split_array(original_array, 3, axis=1)
for sub_array in split_arrays:
    print(sub_array)


[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


Q.50 Write a function that inserts and then deletes elements from a given array at specified indices. original_array = np.array([1, 2, 3, 4, 5])
 indices_to_insert = [2, 4]
 values_to_insert = [10, 11]
 indices_to_delete = [1, 3].

In [66]:
import numpy as np
# Function to insert and then delete elements from an array
def modify_array(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        array = np.insert(array, index, value)
    # Delete elements at specified indices
    array = np.delete(array, indices_to_delete)
    return array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
modified_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)


[ 1 10 11  4  5]


Q.51 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [67]:
import numpy as np

arr1 = np.random.randint(1, 11, size=10)  

arr2 = np.arange(1, 11)  

result = np.add(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result)


arr1: [ 5  6  5  6  8 10  9  5  4  5]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise addition: [ 6  8  8 10 13 16 16 13 13 15]


Q.52 Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [68]:
import numpy as np
# Create the arrays
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
# Subtract arr2 from arr1 element-wise
result = arr1 - arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


Q.53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [69]:
import numpy as np
# Create arr1 with random integers
arr1 = np.random.randint(1, 10, size=5)
# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
# Perform element-wise multiplication
result = arr1 * arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)


arr1: [9 7 4 4 1]
arr2: [1 2 3 4 5]
result: [ 9 14 12 16  5]


Q.54 Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2

In [70]:
import numpy as np
# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)
# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
# Perform element-wise division
result = arr1 / arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
result: [2. 2. 2. 2. 2.]


Q.55 Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

In [71]:
import numpy as np
# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)
# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
# Perform element-wise division
result = arr1 / arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
result: [2. 2. 2. 2. 2.]


Q.56 Write a function that counts the occurrences of a specific substring within a NumPy array of strings. arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']).

In [72]:
import numpy as np
def count_substring_occurrences(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring_occurrences(arr, substring)
print(count)


[1 0 1 0 1]


Q.57 Write a function that extracts uppercase characters from a NumPy array of strings. arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']).

In [73]:
import numpy as np
def extract_uppercase(arr):
    # Create an empty list to store the uppercase characters
    uppercase_chars = []
    # Iterate over each string in the array
    for string in arr:
        # Extract uppercase characters and add them to the list
        uppercase_chars.extend([char for char in string if char.isupper()])
    return np.array(uppercase_chars)
# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)


['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


Q.58 Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [74]:
import numpy as np
def longest_string_length(arr):
    # Find the longest string in the array
    longest_string = max(arr, key=len)
    # Return the length of the longest string
    return len(longest_string)
# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))  # Output: 9


9


Q.59 Write a function that concatenates strings in a NumPy array element-wise. 
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])


In [75]:
import numpy as np
def concatenate_arrays(arr1, arr2):
    return np.char.add(arr1, arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_arrays(arr1, arr2)
print(result)


['HelloOpen' 'WorldAI']


Q.60 Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [2]:
import numpy as np
def longest_string_length(arr):
    
    longest_string = max(arr, key=len)
    
    return len(longest_string)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))  #


9


Q.61 Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [3]:
import numpy as np
# Generate a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)
# Compute the mean
mean = np.mean(dataset)
# Compute the median
median = np.median(dataset)
variance = np.var(dataset)
# Compute the standard deviation
std_deviation = np.std(dataset)
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [381 462 743 258 919 401 595 421 861 906 681 971 153 854 551 720 963 515
  65 252 576 904  83 339 227 408 496 620 594 410  96 564 260 560 447 864
 236 182 418 407 917 722 933 508 888 290 231 384 659 474 856 450 278 590
 768 262   4 212 244 386 422  72  43 752 466 924 234 654 356 916 576 833
 299 876  60 739  48 855 322 239 651 271 687 895 427 216 596 605 682 615
 830 647 243 544 341 631 879 522 610 611]
Mean: 516.08
Median: 518.5
Variance: 68310.85360000002
Standard Deviation: 261.36345115566564


Q.62 Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
import numpy as np
# Generate an array of 50 random numbers between 1 and 100
random_numbers = np.random.randint(1, 101, size=50)
# Calculate the 25th and 75th percentiles
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)
print("Random Numbers:", random_numbers)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Q.63 Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [4]:
import numpy as np
# Create two arrays representing two sets of variables
array1 = np.random.rand(50)
array2 = np.random.rand(50)
# Compute the correlation coefficient between the arrays
correlation_matrix = np.corrcoef(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Correlation Coefficient Matrix:\n", correlation_matrix)


Array 1: [0.85865952 0.64811818 0.37215349 0.18810729 0.50157076 0.1975407
 0.40709303 0.19244211 0.02537671 0.38314646 0.29139647 0.74551409
 0.39813585 0.29960248 0.36967771 0.54931372 0.46535237 0.08262567
 0.78150887 0.70815699 0.29410058 0.89672475 0.8182853  0.91778521
 0.97114056 0.55997813 0.85993384 0.89090974 0.4657751  0.7281846
 0.04217961 0.91195679 0.82084585 0.4207749  0.20729559 0.54259668
 0.42347823 0.78175976 0.25315881 0.82669019 0.36943989 0.69525427
 0.40097385 0.31546892 0.79042585 0.03048251 0.59570182 0.44322321
 0.71573296 0.42390138]
Array 2: [0.09879895 0.6316025  0.52595655 0.76782759 0.59245399 0.60689816
 0.3319074  0.83837009 0.06991582 0.61987592 0.61943972 0.32533845
 0.74121097 0.24588349 0.60747535 0.2021329  0.67362449 0.21405509
 0.17101039 0.21049198 0.44270678 0.53281042 0.86050249 0.31492124
 0.01309531 0.41943317 0.45008771 0.79005134 0.9804702  0.14730352
 0.13944742 0.74908661 0.30006788 0.61394444 0.16626514 0.44185773
 0.87082637 0.6605493 

Q.64 Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [5]:
import numpy as np
# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])
# Perform matrix multiplication
result = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Result of Matrix Multiplication:
 [[ 58  64]
 [139 154]]


Q.65 Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [6]:
import numpy as np
# Create an array of 50 integers between 10 and 1000
random_integers = np.random.randint(10, 1001, size=50)
# Calculate the percentiles and quartiles
percentile_10 = np.percentile(random_integers, 10)
percentile_50 = np.percentile(random_integers, 50)  # This is also the median
percentile_90 = np.percentile(random_integers, 90)
quartile_1 = np.percentile(random_integers, 25)  # First quartile (Q1)
quartile_3 = np.percentile(random_integers, 75)  # Third quartile (Q3)
print("Random Integers:", random_integers)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", quartile_1)
print("Third Quartile (Q3):", quartile_3)


Random Integers: [ 682  930  782  383  719  866  676  884  566  111  628  690  444  790
  509  964  496  248   13  794  645  243  100 1000  172  410  647  274
  296  351  649  180  478  612  819  125  544  217  659  654   70  307
  845  586  189  982   24  248  222  784]
10th Percentile: 123.60000000000001
50th Percentile (Median): 555.0
90th Percentile: 867.8000000000001
First Quartile (Q1): 248.0
Third Quartile (Q3): 711.75


Q.66 Create a NumPy array of integers and find the index of a specific element.

In [7]:
import numpy as np
# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Specify the element to find
element_to_find = 50
# Find the index of the specific element
index = np.where(array == element_to_find)[0][0]
print("Array:", array)
print("Index of element", element_to_find, ":", index)


Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 50 : 4


Q.67 Generate a random NumPy array and sort it in ascending order.

In [8]:
import numpy as np
# Generate a random NumPy array of 10 elements
random_array = np.random.randint(1, 101, size=10)
# Sort the array in ascending order
sorted_array = np.sort(random_array)
print("Random Array:", random_array)
print("Sorted Array:", sorted_array)


Random Array: [ 49  62  88  91  46  47  73  70 100  79]
Sorted Array: [ 46  47  49  62  70  73  79  88  91 100]


Q.68 Filter elements >20  in the given NumPy array. 
arr = np.array([12, 25, 6, 42, 8, 30])

In [9]:
import numpy as np
# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])
# Filter elements greater than 20
filtered_arr = arr[arr > 20]
print("Original Array:", arr)
print("Filtered Array (elements > 20):", filtered_arr)


Original Array: [12 25  6 42  8 30]
Filtered Array (elements > 20): [25 42 30]


Q.69 Filter elements which are divisible by 3 from a given NumPy array. 
arr = np.array([1, 5, 8, 12, 15])

In [10]:
import numpy as np
# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])
# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]
print("Original Array:", arr)
print("Filtered Array (elements divisible by 3):", filtered_arr)


Original Array: [ 1  5  8 12 15]
Filtered Array (elements divisible by 3): [12 15]


Q.70 Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array. 
arr = np.array([10, 20, 30, 40, 50])

In [11]:
import numpy as np
# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])
# Filter elements that are ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Array (elements ≥ 20 and ≤ 40):", filtered_arr)


Original Array: [10 20 30 40 50]
Filtered Array (elements ≥ 20 and ≤ 40): [20 30 40]


Q.71 For the given NumPy array, check its byte order using the `dtype` attribute byteorder. 
arr = np.array([1, 2, 3])

In [17]:
import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print(f"The byte order of the array is: {byte_order}")


The byte order of the array is: =


Q.72 For the given NumPy array, perform byte swapping in place using `byteswap()`. 
arr = np.array([1, 2, 3], dtype=np.int32)

In [19]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)
# Perform byte swapping in place
arr.byteswap(inplace=True)
print("Array after byte swapping:", arr)



Array after byte swapping: [16777216 33554432 50331648]


Q.73 For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`. 
arr = np.array([1, 2, 3], dtype=np.int32)

In [23]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.view(arr.dtype.newbyteorder())

print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)



Original array: [1 2 3]
Swapped byte order array: [16777216 33554432 50331648]


Q.74 For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`. 
arr = np.array([1, 2, 3], dtype=np.int32)

In [26]:
import numpy as np
# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)
# Check the system's endianness
if np.little_endian:
    # If the system is little-endian, swap to big-endian
    swapped_arr = arr.view(arr.dtype.newbyteorder('<'))
else:
    # If the system is big-endian, swap to little-endian
    swapped_arr = arr.view(arr.dtype.newbyteorder('<'))
print("Original Array:", arr)
print("Swapped Byte Order Array:", swapped_arr)


Original Array: [1 2 3]
Swapped Byte Order Array: [1 2 3]


Q.75 For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`. 
arr = np.array([1, 2, 3], dtype=np.int32)

In [27]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the byte order of the array
byte_order = arr.dtype.byteorder

# Determine if byte swapping is necessary
if byte_order == '=':
    print("The array is in native byte order. No byte swapping is necessary.")
elif (byte_order == '<' and not np.little_endian) or (byte_order == '>' and np.little_endian):
    print("Byte swapping is necessary.")
else:
    print("No byte swapping is necessary.")

print("Array:", arr)
print("Byte Order:", byte_order)


The array is in native byte order. No byte swapping is necessary.
Array: [1 2 3]
Byte Order: =


Q.76 Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [28]:
import numpy as np

# Create the original array
arr1 = np.arange(1, 11)

# Create a copy of the original array
copy_arr = arr1.copy()

# Modify an element in the copied array
copy_arr[0] = 99

# Print both arrays to check if the original array is affected
print("Original array (arr1):", arr1)
print("Copied and modified array (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Copied and modified array (copy_arr): [99  2  3  4  5  6  7  8  9 10]


Q.77 Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [29]:
import numpy as np

# Create a 2D array with random integers
matrix = np.random.randint(1, 100, size=(3, 3))

# Extract a slice from the matrix
view_slice = matrix[1:, 1:]

# Modify an element in the slice
view_slice[0, 0] = 999

# Print the original matrix and the slice to observe the changes
print("Original matrix:\n", matrix)
print("View slice:\n", view_slice)


Original matrix:
 [[ 99  11  89]
 [ 30 999  15]
 [ 81  22  54]]
View slice:
 [[999  15]
 [ 22  54]]


Q.78 Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


In [30]:
import numpy as np

# Create the array_a with shape (4, 3) and sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice view_b from array_a
view_b = array_a[:, 1:3]

# Broadcast the addition of 5 to view_b
view_b += 5

# Check if it alters the original array_a
print("array_a after broadcasting addition to view_b:\n", array_a)


array_a after broadcasting addition to view_b:
 [[ 1  7  8]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


Q.79 Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [31]:
import numpy as np

# Create the orig_array with shape (2, 4) and values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 99

# Check if it reflects changes in the original orig_array
print("orig_array after modifying reshaped_view:\n", orig_array)


orig_array after modifying reshaped_view:
 [[99  2  3  4]
 [ 5  6  7  8]]


Q.80 Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.


In [32]:
import numpy as np

# Create the data array with shape (3, 4) and random integers
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Modify an element in data_copy
if data_copy.size > 0:
    data_copy[0] = 99

# Check if it affects the original data
print("Original data array:\n", data)
print("Modified data_copy array:\n", data_copy)


Original data array:
 [[9 2 7 9]
 [9 2 5 1]
 [6 6 9 3]]
Modified data_copy array:
 [99  7  9  9  6  6  9]


Q.81 Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [33]:
import numpy as np

# Create two matrices A and B of shape (3, 3) with integers
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform addition
addition_result = A + B

# Perform subtraction
subtraction_result = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition of A and B:\n", addition_result)
print("Subtraction of A and B:\n", subtraction_result)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition of A and B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction of A and B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


Q.82 Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.


In [34]:
import numpy as np

# Create matrix C of shape (3, 2) with integers
C = np.array([[1, 2], [3, 4], [5, 6]])

# Create matrix D of shape (2, 4) with integers
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

# Perform matrix multiplication
result = np.matmul(C, D)

print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Result of matrix multiplication (C @ D):\n", result)


Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Matrix D:
 [[ 7  8  9 10]
 [11 12 13 14]]
Result of matrix multiplication (C @ D):
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


Q.83 reate a matrix `E` and find its transpose.

In [35]:
import numpy as np

# Create the matrix E
E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the transpose of matrix E
E_transpose = E.T

print("Matrix E:\n", E)
print("Transpose of matrix E:\n", E_transpose)


Matrix E:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of matrix E:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Generate a square matrix `F` and compute its determinant.


In [36]:
import numpy as np

# Create a square matrix F of shape (3, 3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of matrix F
det_F = np.linalg.det(F)

print("Matrix F:\n", F)
print("Determinant of matrix F:", det_F)


Matrix F:
 [[4 5 2]
 [3 9 7]
 [9 3 5]]
Determinant of matrix F: 192.0


Create a square matrix `G` and find its inverse.

In [37]:
import numpy as np

# Create a square matrix G of shape (3, 3) with random integers
G = np.random.randint(1, 10, size=(3, 3))

# Compute the inverse of matrix G
G_inverse = np.linalg.inv(G)

print("Matrix G:\n", G)
print("Inverse of matrix G:\n", G_inverse)


Matrix G:
 [[6 1 1]
 [9 8 8]
 [4 9 7]]
Inverse of matrix G:
 [[ 0.20512821 -0.02564103  0.        ]
 [ 0.3974359  -0.48717949  0.5       ]
 [-0.62820513  0.64102564 -0.5       ]]
